services:
  admin.blog_article:
    class: App\Admin\BlogArticleAdmin
    arguments: [~, App\Application\Sonata\NewsBundle\Entity\Post, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: menu.blog, group: menu.group_name.blog }